version: '3.8'

services:
  app:
    image: ruby:2.5.7
    volumes:
      - ..:/workspace
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: "mongodb://mongo:27017/myapp"
      REDIS_URL: "redis://redis:6379/0"
    command: /bin/bash -c "while sleep 1000; do :; done"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:5540"
    depends_on:
      - redis
volumes:
  mongo-data:
  redis-data: